# Heatmap for VorteX Clusters

## Load data

```{r}
case = 5

if(case == 1) { ## CD3+ Healthy donors vs New
    data = read.table('vortex-in-manuscript/HDvsCD_CD3+_12k_Apr2019_allSCs.csv.gz', sep=',', header=T)
    prefix_out = 'outputs/CD3+ Donor vs New - '
    data$Event.Name = NULL
    data$Comment = NULL
} else if(case == 2) { ## CD3+ New vs Relapsed/Refractory
    data = read.table('vortex-in-manuscript/CDvsRR_CD3+_allSCs.csv.gz', sep=',', header=T)
    prefix_out = 'outputs/CD3+ New vs RR - '
    data$Event.Name = NULL
    data$Comment = NULL
} else if(case == 3) { ## CD3- Healthy donors vs New
    data = read.table('vortex-in-manuscript/HDvsCD_CD3-_12k_AllSCs.csv.gz', sep=',', header=T)
    prefix_out = 'outputs/CD3- Donor vs New - '
    data$Event.Name = NULL
    data$Comment = NULL
} else if(case == 4) { ## CD3- New vs Relapsed/Refractory
    data = read.table('vortex-in-manuscript/CM205_CDvsRR_CD3-_allSCs.csv.gz', sep=',', header=T)
    prefix_out = 'outputs/CD3- New vs RR - '
    data$Event.Name = NULL
    data$Comment = NULL
} else if(case == 5) { ## CD3- RLN vs HL
    data = read.table('vortex-clusters/Zumla CD3- tumor and normal controls K=35 cluster.csv.gz', sep=',', header=T)
    prefix_out = 'outputs/tumor_normal_CD3-_K35 - '
    data$Event.Name = NULL
    data$Comment = NULL
}

colors = c("#4F81BD", "#C05058", "#9BBB59", "#69269D", "#F79646", "#1D4E31", "#F40BF4", "#00FFFF", "#008098", "#FF4500", "#FF0000", "#00FF00", "#0000FF", "#000000", "#CDBE70", "#00BFFF", "#8B008B", "#ADFF2F", "#EE7600", "#71C671", "#BB1968", "#683509", "#55A8F7", "#B50127", "#F628F0", "#8DF2E9", "#EF7C65", "#E95828", "#4B5E81", "#DD1D8A", "#C595A8", "#0A28C2", "#609F23", "#E1B173", "#CE0101", "#DA8505", "#BEB424", "#467B13", "#8B9C93", "#F43446", "#9F302F", "#0002AE", "#297C2D", "#7C8A20", "#F9213E", "#3464D8", "#37686E", "#F33B85", "#E36309", "#45971C", "#A73A1E", "#FDA796", "#FBF634", "#435F5C", "#76E055", "#4A710D", "#812EFF", "#A3A147", "#E85781", "#447D1D", "#6D234E", "#8BB77E", "#F60335", "#5B2C3E", "#8CCD8E", "#1C9684", "#CA86B2", "#5C3471", "#41B3C7", "#2C39B3", "#FBEDCD", "#BDD617", "#296FA3", "#5202A7", "#A15F35", "#E9E14D", "#B5CEB9", "#6D820E", "#FC2327", "#98B5F2", "#D2821F", "#A79DB5", "#7B4419", "#109D97", "#074897", "#861242", "#1247AE", "#A4475A", "#9A27D9", "#5D5A90", "#993D4A", "#04E0D3", "#BE8A6C", "#A460F8", "#45DCBA", "#CAE3D7", "#0B6F75", "#56DC4C", "#E6150F", "#8EC342", "#6D98FF", "#F70FA1", "#968D91", "#8BA933", "#E8FF3F", "#B53FE0", "#B4DA56", "#C79B37", "#50E006", "#D57343", "#5E9376", "#212D0A", "#ADD3B7", "#93BEEA", "#EDB997", "#A4A402", "#1C8BC6", "#D54EBE", "#E15EA1", "#8EEDE0", "#3241C1", "#3D286C", "#0A9060", "#0CC9E5", "#B64A1C", "#CCC386", "#076A51", "#DCAAF0", "#6D7866", "#10BE8C", "#5D13C3", "#A652DB", "#83C97A", "#02210A", "#087371", "#44B1F2", "#B85FC7", "#0749C5", "#C88EF7", "#F7FFC7", "#3D5171", "#BF21A8", "#3CA6A7", "#2B92E6", "#8E0940", "#60EB64", "#B96AC6", "#0B3EB6", "#2C9171", "#74D478", "#9A73A3", "#7C4D75", "#10CCF0", "#554494", "#3A854D", "#685F55", "#DB23CE", "#0D6319", "#43AE08", "#6AAB27", "#137D9B", "#FD2DFA", "#0727B5", "#EE4775", "#1DDBB0", "#185934", "#3A652A", "#5698D5", "#CF6383", "#AE597C", "#0D129B", "#F8AEA9", "#95E25E", "#30F28D", "#AFA839", "#507100", "#B51B07", "#FBA899", "#5087D0", "#302777", "#743351", "#E48C27", "#85BF50", "#8BB2BE", "#18E1F5", "#5D21AD", "#067415", "#460D6A", "#7832D1", "#FAF85E", "#59DF45", "#0D02B9", "#CB9119", "#0AD15C", "#BF1861", "#391B76", "#C4EE35", "#3CF1A3", "#0779BF", "#E8A280", "#F01818", "#24F58A", "#D18236", "#B2D5A8", "#41D3A3", "#4CB728", "#CD5C76", "#771EE7", "#820FBE", "#910E5E", "#8FEF5E", "#90E1EE", "#E1B30F", "#2412CE", "#3AA938", "#49A5B4", "#4BEFE2", "#0C8B1B", "#B3FC2E", "#F258F2", "#0A5F3F", "#D0CB45", "#B57B77", "#B7CDE7", "#156C7A", "#FEF6E7", "#3CE774", "#BE7B8C", "#10741B", "#B9E4BA", "#DD7FCC", "#A0592A", "#2154E4", "#816E2A", "#219BAB", "#FD843E", "#8D5FEA", "#846133", "#2C5822", "#1D7ACB", "#E0CC69", "#958785", "#A26F29", "#4F3F44", "#DA4E0C", "#03E329", "#07B79C", "#D34A62", "#14A8C5", "#3A5B3D")

```

## Load library

```{r}
library(ggplot2)
library(ggpubr)
library(pheatmap)
library(reshape2)
library(RColorBrewer)
library(gplots)
library(pheatmap)

```

## Plot heatmap

```{r, fig.height=8, fig.width=8}
dataFromXshift = data
dataFromXshift$Event.Name = NULL
dataFromXshift$Comment = NULL

cid = sort(unique(data$ClusterID))

colnames(dataFromXshift)=gsub("MHC_I","MHC.I",colnames(dataFromXshift))
colnames(dataFromXshift)=gsub("MHCII","MHC.II",colnames(dataFromXshift))
colnames(dataFromXshift)=gsub("^.+?_([^_]+)$","\\1",colnames(dataFromXshift))
colnames(dataFromXshift)=gsub("c.Parp","cParp",colnames(dataFromXshift))
colnames(dataFromXshift)=gsub("HLA.a.b.c","HLAabc",colnames(dataFromXshift))
colnames(dataFromXshift)=gsub("[._]","-",colnames(dataFromXshift))

if(case == 1) {
    excluded = c('LAG3', 'Pax5', 'CD14', 'CD33', 'CD68', 'CD163', 'PARP', 'CD45', 'DNA1', 'DNA2', 'Viabilty', 'X138Ba')
    dataFromXshift = dataFromXshift[, ! (colnames(dataFromXshift) %in% excluded)]
} else if(case == 2) {
    excluded = c('LAG3', 'Pax5', 'CD14', 'CD33', 'CD68', 'CD163', 'PARP', 'CD45', 'DNA1', 'DNA2', 'Viabilty')
    dataFromXshift = dataFromXshift[, ! (colnames(dataFromXshift) %in% excluded)]
} else if(case == 3) {
    excluded = c('LAG3', 'PARP', 'CD45', 'DNA1', 'DNA2', 'Viabilty')
    dataFromXshift = dataFromXshift[, ! (colnames(dataFromXshift) %in% excluded)]
} else if(case == 4) {
    excluded = c('LAG3', 'PARP', 'CD45', 'DNA1', 'DNA2', 'Viabilty', 'X', 'X-1', 'X-2', 'X-3', 'X-4', 'X-5')
    dataFromXshift = dataFromXshift[, ! (colnames(dataFromXshift) %in% excluded)]
} else if(case == 5) {
    colnames(dataFromXshift)=gsub("(^.+)-([^-]+)$","\\1",colnames(dataFromXshift))
}

medianAbValueByCluster=aggregate(dataFromXshift[,5:ncol(dataFromXshift)],by=list(dataFromXshift$ClusterID),median)
meanAbValueByCluster=aggregate(dataFromXshift[,5:ncol(dataFromXshift)],by=list(dataFromXshift$ClusterID),mean)

Stdev=data.frame(apply(medianAbValueByCluster[,2:ncol(medianAbValueByCluster)],2, sd))
zeroSD=rownames(Stdev[Stdev[,1]==0,,drop=FALSE])
medianAbValueByCluster[,colnames(medianAbValueByCluster) %in% zeroSD]<- meanAbValueByCluster[,colnames(meanAbValueByCluster) %in% zeroSD]

# set the clusterid as the rownames for the new dataframe with the medians
rownames(medianAbValueByCluster)=medianAbValueByCluster[,1]

# set up color scheme for samples
colorMatrix=cbind.data.frame('cluster'=unique(dataFromXshift$ClusterID))
colorMatrix$color=colors[match(colorMatrix$cluster, cid)]

# merge the data to colors
dataWithColors=merge(colorMatrix,medianAbValueByCluster,by.x='cluster',by.y=1)
rownames(dataWithColors)=dataWithColors$cluster

# clustering on ab axis part generates the distance matrix for the data frame
dissimilarity <- 1 - cor(dataWithColors[,3:ncol(dataWithColors)],method='pearson')
distance <- as.dist(dissimilarity)
cluster=hclust(distance, method = "average")

# clustering on cluster uses t() to transpose the data frame.
dissimilarityDim2 <- 1 - cor(t(dataWithColors[,3:ncol(dataWithColors)]),method='pearson')
distanceDim2 <- as.dist(dissimilarityDim2)
clusterDim2=hclust(distanceDim2, method = "average")
AbOrderForHM=cluster$label[cluster$order]

# creates a own color palette from red to blue
my_palette <- colorRampPalette(c("#0000FF", "white", "#FF0000"))(n=59)
col_breaks = c(seq(-4,-1,length=20),  # for blue
               seq(-0.99,0.99,length=20),   # for white
               seq(1,4,length=20))      #red

medianAbValueByClusterCentered=scale(dataWithColors[,3:ncol(dataWithColors)],center=TRUE,scale=TRUE)
medianAbValueByClusterCentered[medianAbValueByClusterCentered > 4] <- 4
medianAbValueByClusterCentered[medianAbValueByClusterCentered < -4 ] <- -4

medianAbValueByClusterCentered=cbind.data.frame(
            'cluster'=dataWithColors$cluster,
            'cluster1'=dataWithColors$color,
            'cluster2'=dataWithColors$color,
            medianAbValueByClusterCentered)
```

## Annotate clusters

```{r}
cnames = rownames(medianAbValueByClusterCentered)
landmarks = cnames

if(case == 1) {
    id_map = list(
        c('7497', 'CD4 Th17 CXCR5+ CM'),
        c('7525', 'CD4 Th0 CXCR5+ CM'),
        c('7508', 'CD4 Th2 CM (1)'),
        c('7514', 'CD4 Th17 CM'),
        c('7507', 'CD4 CD161+ EM'),
        c('7529', 'CD4 Th2 EM'),
        c('7513', 'CD8 Treg'),
        c('7495', 'CD4 Treg'),
        c('7503', 'CD4 Treg'),
        c('7505', 'Other'),
        c('7524', 'CD4 Naive'),
        c('7520', 'CD8 Naive'),
        c('7521', 'CD4 Naive'),
        c('7522', 'CD4 Naive'),
        c('7488', 'Not T cell'),
        c('7530', 'CD8 Naive'),
        c('7515', 'DN MAIT (1)'),
        c('7493', 'CD4 Th1 EM GrB+'),
        c('7518', 'CD4 Th1 Temra GrB+'),
        c('7516', 'CD8 Tc1 Temra (1)'),
        c('7523', 'CD8 Tc1 Temra (1)'),
        c('7517', 'CD4 non-classical Th1 EM'),
        c('7499', 'CD8 CD161+'),
        c('7502', 'DN MAIT (2)'),
        c('7487', 'Not T cell'),
        c('7492', 'CD8 Tc1 Temra (3)'),
        c('7510', 'CD8 Tc1 Temra (2)'),
        c('7489', 'CD8 Tc1 EM (1)'),
        c('7490', 'CD8 Tc1 EM (1)'))
} else if(case == 2) {
    id_map = list(
        c('5703', 'CD8 CD161+'),
        c('5706', 'DN MAIT (2)'),
        c('5711', 'CD8 Tc1 Temra (2)'),
        c('5731', 'CD8 Tc1 Temra (1)'),
        c('5723', 'CD8 Tc1 EM (1)'),
        c('5724', 'CD8 Tc1 EM (1)'),
        c('5704', 'CD4 Non classical Th1 EM GrB+'),
        c('5732', 'CD4 Th1 EM GrB+'),
        c('5737', 'CD8 Treg'),
        c('5700', 'CD4 Treg'),
        c('5707', 'CD4 Th2 EM'),
        c('5740', 'CD4 Th2-like EM'),
        c('5739', 'CD4 Th17 CXCR5+ CM'),
        c('5708', 'CD4 Th17 CM'),
        c('5710', 'CD4 Th2 CM (1)'),
        c('5721', 'CD8 Tc1 EM (2)'),
        c('5734', 'CD4 Th2 CM (2)'),
        c('5712', 'CD4 Na誰ve'),
        c('5713', 'CD4 Na誰ve'),
        c('5702', 'CD4 Na誰ve'),
        c('5705', 'CD8 Na誰ve'))
} else if(case == 3) {
    id_map = list(
        c('6615', 'CD68+ CD4+ GrB+'),
        c('6625', 'monocytic dendritic cell'),
        c('6635', 'non-classical monocyte'),
        c('6664', 'classical monocyte'),
        c('6621', 'classical monocyte'),
        c('6691', 'classical monocyte'),
        c('6669', 'classical monocyte'),
        c('6651', 'classical monocyte'),
        c('6657', 'classical monocyte'),
        c('6671', 'intermediate monocyte'),
        c('6670', 'B cell (1)'),
        c('6677', 'B cell (1)'),
        c('6686', 'B cell (3)'),
        c('6613', 'B cell (2)'),
        c('6622', 'B cell (2)'),
        c('6624', 'B cell (2)'),
        c('6642', 'B cell (2)'),
        c('6688', 'CD8+ T cell'),
        c('6632', 'NK cell (3)'),
        c('6616', 'NK cell (4)'),
        c('6617', 'NK cell (3)'),
        c('6634', 'NK cell (1)'),
        c('6630', 'NK cell (3)'),
        c('6683', 'NK cell (2)'),
        c('6661', 'CD56+CD16+PD-1+GrB-'),
        c('6644', 'CD16+'),
        c('6672', 'Neutrophil'),
        c('6689', 'Neutrophil'),
        c('6692', 'CD8+ T cell'),
        c('6682', 'CD4+ T cell'),
        c('6684', 'CD4+ T cell'))
} else if(case == 4) {
    id_map = list(
        c('711', 'classical monocyte'),
        c('716', 'classical monocyte'),
        c('746', 'classical monocyte'),
        c('729', 'CD68+ CD4+ GrB+'),
        c('742', 'non classical monocyte'),
        c('741', 'CD14+ dendritic cell'),
        c('719', 'B cell (3)'),
        c('733', 'B cell (2)'),
        c('726', 'CD8+ T cell'),
        c('735', 'NK cell (4)'),
        c('720', 'NK cell (1)'),
        c('714', 'NK cell (3)'),
        c('725', 'NK cell (2)'),
        c('705', 'CD56+CD16+PD-1+GrB-'),
        c('707', 'Neutrophil'),
        c('738', 'Neutrophil'),
        c('715', 'Other'),
        c('732', 'Other'))
} else if(case == 5) {
    id_map = list(
        c('3336', ' '),
        c('3329', ' '),
        c('3339', ' '),
        c('3341', ' '),
        c('3342', ' '),
        c('3331', ' '),
        c('3325', ' '),
        c('3326', ' '))
} else {
    id_map = lapply(landmarks, function(x) c(x, ''))
}

id_map = t(as.data.frame(id_map))
old_id = as.character(id_map[,1])
new_id = as.character(id_map[,2])
new_id = paste(old_id, new_id)
landmarks[match(old_id, cnames)] = new_id
```

## Plot the whole heatmap

```{r}
mat_row <- data.frame(Cluster=cnames)
rownames(mat_row) <- cnames
mat_colors <- list(Cluster=as.character(medianAbValueByClusterCentered$cluster1))
names(mat_colors$Cluster) <- cnames

mat = as.matrix(medianAbValueByClusterCentered[, 4:ncol(medianAbValueByClusterCentered)])

pheatmap(
  mat               = mat,
  color             = my_palette,
  border_color      = NA,
  breaks = col_breaks,
  annotation_row    = mat_row,
  annotation_colors = mat_colors,
  annotation_legend = FALSE,
  clustering_distance_rows = "correlation",
  clustering_distance_cols = "correlation",
  filename = paste0(prefix_out, 'all_heatmap.pdf'),
  height   = 7 * nrow(mat)/80 + 2,
  width    = 5 * ncol(mat)/50 + 2,
  fontsize = 7
)

write.csv(mat, paste0(prefix_out, 'all_values.csv'))
```

## Plot selected clusters

```{r}
mat_row1 <- data.frame(Cluster=cnames[landmarks != cnames])
rownames(mat_row1) <- cnames[landmarks != cnames]
cols = as.character(medianAbValueByClusterCentered$cluster1)[landmarks != cnames]
mat_colors1 <- list(Cluster=cols)
names(mat_colors1$Cluster) <- cnames[landmarks != cnames]

mat = as.matrix(medianAbValueByClusterCentered[landmarks != cnames, 4:ncol(medianAbValueByClusterCentered)])

pheatmap(
  mat               = mat,
  color             = my_palette,
  border_color      = NA,
  breaks = col_breaks,
  labels_row = landmarks[landmarks != cnames],
  annotation_row    = mat_row1,
  annotation_colors = mat_colors1,
  clustering_distance_rows = "correlation",
  clustering_distance_cols = "correlation",
  annotation_legend = FALSE,
  drop_levels       = FALSE,
  filename = paste0(prefix_out, 'sel_heatmap.pdf'),
  height   = 7 * nrow(mat)/70 + 2,
  width    = 5 * ncol(mat)/40 + 2,
  fontsize = 7
)

write.csv(mat, paste0(prefix_out, 'sel_values.csv'))
```
